var AccountPoints = {
  "termsandconditions": {
    "head": "Terms & Conditions",
    "lastupdated": "Last Updated On Sep 2023",
    "para": ["The App, including subsidiaries and affiliates (“App or Company Owner” or “we” or “us” or “our”) provides the information contained on the App or any of the pages comprising the App (App) to visitors (“visitors”) (cumulatively referred to as “you” or “your” hereinafter) subject to the terms and conditions set out in these App terms and conditions, the privacy policy and any other relevant terms and conditions, policies and notices which may be applicable to a specific section or module of the App.", "Welcome to our App. If you continue to browse and use this App you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern V Studio''s relationship with you in relation to this App.", "The term 'V Studio' or 'us' or 'we' refers to the owner of the App whose registered/operational office is 11/4 periya pelli st Santhome Chennai 600 028 Chennai TAMIL NADU 600028. The term 'you' refers to the user or viewer of our App.", "We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time"],
    "keypoint": ["The content of the pages of this App is for your general information and use only. It is subject to change without notice.", "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this App for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.", "Your use of any information or materials on this App is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this App meet your specific requirements.", "This App contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.", "All trademarks reproduced in this App which are not the property of, or licensed to, the operator are acknowledged on the App.", "Unauthorized use of this App may give rise to a claim for damages and/or be a criminal offense.", "From time to time this App may also include links to other Apps. These links are provided for your convenience to provide further information.", "You may not create a link to this App from another App or document without V Studio’s prior written consent.", "Your use of this App and any dispute arising out of such use of the App is subject to the laws of India or other regulatory authority."], 
  },
  "privacypolicy": {
    "head": "Privacy Policy",
    "lastupdated": "Last Updated On Sep 2023",
    "para": ["This privacy policy sets out how V Studio uses and protects any information that you give V Studio when you use this App.", "V Studio is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, and then you can be assured that it will only be used in accordance with this privacy statement.", "V Studio may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes."],
    "collect": ["Name and job title", "Contact information including email address", "Demographic information such as postcode, preferences and interests", "Other information relevant to customer surveys and/or offers"],
    "gather": ["Internal record keeping.", "We may use the information to improve our products and services.", "We may periodically send promotional emails about new products, special offers or other information which we think you may find interesting using the email address which you have provided.", "From time to time, we may also use your information to contact you for market research purposes. We may contact you by email, phone, fax or mail. We may use the information to customise the website according to your interests."],
    "cookies": ["A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyses web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences.", "We use traffic log cookies to identify which pages are being used. This helps us analyses data about webpage traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system.", "Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us.", "You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website."],
    "personalInfo": ["whenever you are asked to fill in a form on the website, look for the box that you can click to indicate that you do not want the information to be used by anybody for direct marketing purposes", "if you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by writing to or emailing us at"]
  },
  "refundpolicy": {
    "head": "Cancellation & Refund Policy",
    "lastupdated": "Last Updated On Sep 2023",
    "para": ["No cancellations & Refunds are entertained"],
  },
  "contactus": {
    "head": "Contact us",
    "lastupdated": "Last Updated On Sep 2023",
    "para": ["You may contact us using the information below:", "Merchant Legal entity name: V Studio", "Registered Address: 11/4 periya pelli st Santhome Chennai 600 028 Chennai TAMIL NADU 600028", "Operational Address: 11/4 periya pelli st Santhome Chennai 600 028 Chennai TAMIL NADU 600028", "Telephone No: 9043870363", "E-Mail ID: itsarrowhere380@gmail.com"],
  },
};
